version: "3.9"

networks:
  weather-forecast-net:

services:
  postgres:
    image: "postgres"
    container_name: "weather-forecast-postgres"
    networks:
      - weather-forecast-net
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: "redis"
    container_name: "weather-forecast-redis"
    networks:
      - weather-forecast-net
    ports:
      - 6379:6379