version: "3.9"

services:
  app:
    container_name: weather-forecast
    image: weather-forecast-img
    build:
      context: .
      dockerfile: Dockerfile.setup
    networks:
      - weather-forecast-net
    ports:
      - 5050:80
    environment:
      ConnectionStrings__Postgres: "Host=weather-forecast-postgres;Database=postgres;Username=postgres;password=postgres"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started